name: 02 - Workflow Events
on: 
    push:
    pull_request:
    workflow_dispatch:
    repository_dispatch:
        types: [showthetrigger]    

jobs:
    showthetrigger:
        runs-on: ubuntu-latest
        steps:
           - run: echo "This workflow was triggered by a push event ${{github.event_name}}"

